name: Continous deployment
on: [push, pull_request]

jobs:

  avoid_reduncy: 
    runs-on: ubuntu-18.04
    steps: 
      name: cancel previous redundant builds
      uses: styfle/cancel-workflow-action@0.9.1
      with: 
        access_token: ${{ github.token }}


  build: 
    runs-on: ubuntu-18.04
    steps: 
      uses: actions/checkout@v2
      name: Install Dependencies
        run: npm ci
      name: Build
        run: npm run build
      uses: upload-artifact@v2
        with:
          name: build
          path: build

  test: 
    needs: [build] 
    runs-on: ubuntu-18.04
    steps: 
      name: Checkout
      uses: actions/checkout@v2
      name: Install Dependencies
        run: npm ci
      name: Create artifact
      uses: download-artifact@v2
        with:
          name: build
          path: build
      name: Test
        run: npm run test
        


  deploy_job:
    needs: [test]
    runs-on: ubuntu-18.04
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file to server
        if: ${{ github.event_name == 'push' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'maniutzq'
          server: 'ftp.manikins.io'
          port: 21098
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/home/maniutzq/public_html/'
          args: '-o ConnectTimeout=60'
